# Usamos a imagem completa do Node (não a alpine) para ter mais ferramentas de dev
FROM node:20

# Instala o Angular CLI globalmente
RUN npm install -g @angular/cli

# Define o diretório de trabalho
WORKDIR /app

# Expõe a porta do Angular (4200)
EXPOSE 4200

# O comando padrão deixa o container "vivo" esperando seus comandos
CMD ["tail", "-f", "/dev/null"]